# Generated by Django 5.0.2 on 2024-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_category_pdffile_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default='default_file.pdf', upload_to='doc/'),
        ),
    ]
