# Generated by Django 5.0.2 on 2024-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(upload_to='doc/'),
        ),
    ]
