# Generated by Django 5.0.2 on 2024-02-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_category_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file',
        ),
        migrations.AddField(
            model_name='category',
            name='pdfFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
