# Generated by Django 5.0.2 on 2024-02-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_category_file_category_pdffile_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pdfFile',
        ),
        migrations.AddField(
            model_name='document',
            name='pdfFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
    ]
