# Generated by Django 5.0.2 on 2024-03-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_category_pdffile_document_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdfFile',
        ),
        migrations.AddField(
            model_name='category',
            name='pdfFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='forum.document'),
        ),
    ]
