# Generated by Django 5.0.2 on 2024-03-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_document_pdffile_category_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pdfFile',
        ),
        migrations.AddField(
            model_name='document',
            name='pdfFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='forum.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='documents'),
        ),
    ]
