# Generated by Django 5.0.2 on 2024-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closed_comments',
            field=models.BooleanField(default=False),
        ),
    ]
